### ISSUE TITLE
关于加粗效果的小建议

### ISSUE THREAD

**Issue by ChiayuanYao** [pengx17/logseq-dev-theme#14]
您好！我特别喜欢这个Logseq-dev-theme，

不过有一处显示效果上的小建议：

如果为一级标题设置底色，字体是呈现白色的比如：
<img width="646" alt="image" src="https://user-images.githubusercontent.com/53948170/141610074-4199afaf-efb4-49df-a551-3bdc9787256c.png">
这个时候如果加粗一级标题，在light模式下字体反而会变成黑色，如下图所示：
<img width="706" alt="image" src="https://user-images.githubusercontent.com/53948170/141610120-4cdfdcda-4ee1-4e2e-a498-41421725270b.png">
由于LogSeq提供的看起来都是深色的底色，配上黑色的文字的效果就打了折扣。在Dark模式下则无此问题。

个人是技术小白，因此不太会修改css文件，如果可以的话，是否能告诉我要如何调整呢？

再次感谢您开发这个特别棒的主题！

**Comment by ChiayuanYao** [comment]
我摸索着修改了一下css文件中的字重，问题似乎已经得到解决了，谢谢！

**Comment by pengx17** [comment]
😄 好的, 我会考虑修改一下这个标题颜色的样式

**Comment by ChiayuanYao** [comment]
> 😄 好的, 我会考虑修改一下这个标题颜色的样式

谢谢！

**Comment by pengx17** [comment]
fixed by https://github.com/pengx17/logseq-dev-theme/commit/a7a3778f52d5ac6d2428744b858b09fa617621cd
