### ISSUE TITLE
Broken in 0.4.6

### ISSUE THREAD

**Issue by zhengyu-yang** [pengx17/logseq-dev-theme#15]
After the app is updated to 0.4.6, the main content area can no longer scroll when the theme is applied. Also, the right sidebar can scroll, but there is a blank bar at the bottom of the right sidebar. 
![image](https://user-images.githubusercontent.com/25852061/142085844-f1f0934c-ee39-4f4d-9cf9-cdddd3c8dce4.png)

**Comment by pengx17** [comment]
This is caused by https://github.com/logseq/logseq/commit/955648beeb98e00aefa167c8001c8fee6ed20cd1#diff-0a1590918f1e6dd3d7a862dd75cac598e0dc1ca3bdd790df91a67b5f5ec89f8b, but I am not sure why this is removed in Logseq though.
