### ISSUE TITLE
Tooltip style

### ISSUE THREAD

**Issue by Bad3r** [pengx17/logseq-dev-theme#16]
Hi,

I noticed that the tooltip style on the Dev theme is different from the default theme

Dev Theme:

![](https://user-images.githubusercontent.com/25513724/142262818-fc61ae10-513c-45fc-9631-ea9761eceb15.png)

Default Theme:

![](https://user-images.githubusercontent.com/25513724/142262941-70c9f3ba-d180-4130-a20e-f0d6009b1867.png)

This may have been effected by a recent change, logseq/logseq#3170.

I personally prefer the default theme style, and I am not sure if the change is intentional. I also find that the border color (black) does not match well with the theme color scheme

**Comment by pengx17** [comment]
This is an intentional design. Popups including tooltips like this one all have 2px black borders without arrows, inspired by Figma.
![image](https://user-images.githubusercontent.com/584378/142372411-aebedf08-be28-4b3b-a698-02ddd2073a7f.png)

**Comment by Bad3r** [comment]
Noted. Thank you for the clarification
