### ISSUE TITLE
快速折叠展开功能

### ISSUE THREAD

**Issue by qbosen** [pengx17/logseq-dev-theme#18]
在rr的视频里看到的，大概是这样的效果
![Kapture 2021-11-25 at 14 23 02](https://user-images.githubusercontent.com/15816040/143390453-612856ec-d1fa-41ea-9e30-a7ca2ef23caf.gif)

不知道是主题的功能还是需要logseq支持。

[bilibili原视频](https://www.bilibili.com/video/BV1Vr4y1k7DJ)
[roam repo](https://github.com/JimmyLv/styled-roam)

**Comment by pengx17** [comment]
@qbosen 这个功能需要Logseq本身的支持，主题本身是纯CSS，能做到的东西比较有限
