### ISSUE TITLE
Code Block Language Button

### ISSUE THREAD

**Issue by zhengyu-yang** [pengx17/logseq-dev-theme#20]
The language button (python) is out of the boundary of the empty code block.

![image](https://user-images.githubusercontent.com/25852061/146319656-ae58036a-b3b8-4f9b-8335-bc4ad0e96daa.png)

**Comment by Bad3r** [comment]
Could be related to https://github.com/logseq/logseq/pull/3443

**Comment by Bad3r** [comment]
@pengx17 seems like this has been updated/changed. 
![image](https://user-images.githubusercontent.com/25513724/147765204-22aa0ef5-6c0f-4408-aa56-66b19dbd9a01.png)
One issue I noticed is that one you have only 1 line of code. The language button/label is not in the correct position, or maybe the size needs to be changed.
![image](https://user-images.githubusercontent.com/25513724/147765312-de80457b-0f96-4551-8669-b13d8fab91ea.png)
Notice the space above the label compared to under it.
