### ISSUE TITLE
Calculator block results get out of line with calculations

### ISSUE THREAD

**Issue by Lifeling** [pengx17/logseq-dev-theme#22]
When using the calculator blocks, if calculating more than 1 line, the alignment of calculation and result quickly goes wrong.
![image](https://user-images.githubusercontent.com/1037038/146570585-c369b28b-dc6f-4162-bb92-efde842932cc.png)

**Comment by pengx17** [comment]
@Lifeling seems to be an upstream issue. Let me if I can create a PR for that.

**Comment by pengx17** [comment]
This should have been fixed in https://github.com/pengx17/logseq-dev-theme/releases/tag/v1.22.4

**Comment by ivanddm** [comment]
Thanks a lot for this!

I was wondering when this changes should be reflected at `@import url("https://cdn.jsdelivr.net/gh/pengx17/logseq-dev-theme@main/custom.css");`?

**Comment by pengx17** [comment]
@ivanddm 
I think you can force reload the page by shift+cmd+r the page.

**Comment by ivanddm** [comment]
Yes @pengx17 , that did the trick (force reload). The calculator results are not overflowing any more. Thanks again!
