### ISSUE TITLE
Issue with guideline width and color

### ISSUE THREAD

**Issue by ivanddm** [pengx17/logseq-dev-theme#27]
Since yesterday I started having a thick guideline with a different color. Perhaps is related to some Logseq update?

At the moment I get the following guidelines which make the  bullet threading look off place as well:

<img width="1066" alt="CleanShot 2021-12-30 at 21 17 34@2x" src="https://user-images.githubusercontent.com/20104703/147778358-6713f9e7-05fc-4dfd-b35a-f18a622895c6.png">

I have managed to fix that temporarily with the following CSS:

```css
.block-children {
  border-left-width: 0px;
  margin-left: -1px;
}
```

which makes it look like this:

<img width="1098" alt="CleanShot 2021-12-30 at 21 18 17@2x" src="https://user-images.githubusercontent.com/20104703/147778462-9c760f49-d455-4c28-b118-7afa5dfd611c.png">

I don't have any other modifications on my `custom.css` so I'm assuming I'm not the only one facing this issue. Similar behavior happens with different themes. Hopefully, you can reproduce it as well.

Thanks in advance!

**Comment by Bad3r** [comment]
Did you install the theme from the marketplace or are you using jsdelivr? 
I thik this was already fixed and jsdelivr has not been updating. I switched to [githack](https://raw.githack.com) (development url) and it seems much better than Jsdelivr. 

If you are using jsdelivr can you please comment out your modification above and replace the jsdelivr url with:

https://raw.githack.com/pengx17/logseq-dev-theme/main/custom.css

And see if that fixes the issue.

**Comment by ivanddm** [comment]
@Bad3r Yes, I'm using jsdelivr, probably that's the reason then. 

I just did as you suggested, using https://raw.githack.com/pengx17/logseq-dev-theme/main/custom.css instead and commenting out my modification, and it is working again like a charm 👍🏻... Thanks for that!

Just to be clear, should I keep using githack or the marketplace plugin instead (or they are the same?).

Thanks again!

**Comment by Bad3r** [comment]
> Just to be clear, should I keep using githack or the marketplace plugin instead (or they are the same?).

Githacks will pull the theme directly from this github repo. I personally find it better than the plugin because it's easier to modify the theme using custom.css. At the end they will both give you the same theme. 

Thank you for confirming this issue. Jsdelivr seems to cache their cdn and they do t update. It's been almost a week since this update came out. @pengx17 maybe consider recommending Githacks instead of jsdelivr as it pulls directly from github without catching on a cdn.

**Comment by ivanddm** [comment]
Great, I will keep using `githacks` then. Thanks again for suggesting this @Bad3r . I also noticed that jsdelivr takes some time to update the changes, so githacks should be the way to go 👍🏻.
