### ISSUE TITLE
Ordered list highlighting problem.

### ISSUE THREAD

**Issue by ciallowo** [pengx17/logseq-dev-theme#28]
![image](https://user-images.githubusercontent.com/76084546/147903518-c17424f2-5a83-4767-ac31-e9b47e76a3a9.png)
Some are highlighted, some are not highlighted.

Happy new year, sorry to disturb you.

**Comment by pengx17** [comment]
Hi @ciallowo , this is an issue related to Logseq itself. The title line (first line) is not being correctly parsed. Can you open an issue in logseq instead?

**Comment by ciallowo** [comment]
@pengx17 Thank you, I will go to discord or give feedback on github.
