### ISSUE TITLE
Selected block is not highlighted

### ISSUE THREAD

**Issue by Rahlir** [pengx17/logseq-dev-theme#29]
I am using this theme as suggested in the `README`:
```css
/* This must be the first line of the custom.css with other import rules */
@import url("https://cdn.jsdelivr.net/gh/pengx17/logseq-dev-theme@main/custom.css");

/* You can also add other styles below to override the default theme values */
```
With this, starting in mid-December I think, the selected block is not highlighted. Meaning, for instance typing something and then toggling `Esc`, there is no blue highlight showing me where I was typing before. I already tried: clearing cache, re-indexing the graph, and refreshing the graph. Nothing helped. The only way now to get the highlight is to copy the entire `custom.css` from this repo into my `custom.css`.

**Comment by Rahlir** [comment]
Hmm, I am now seeing that this should have been fixed with [0d9b59b](https://github.com/pengx17/logseq-dev-theme/commit/0d9b59b866427205f7aa07ece1ff32329ed4e207). Perhaps there is something wrong with jsdelivr? Is it updated? If this was an issue on my end, wouldn't clearing the cache work?

**Comment by Bad3r** [comment]
@Rahlir yes I think jsdelivr has not been updating at all. Check the discussion here: https://github.com/pengx17/logseq-dev-theme/issues/27#issuecomment-1003145341

**Comment by Rahlir** [comment]
Ahh, githack works, thank you! Might be worth updating the readme so you don't get new issues from bummers like me 😄

**Comment by Bad3r** [comment]
> Ahh, githack works, thank you! Seems like jsdelivr must be super slow on updating then lol. Might be worth updating the readme so you don't get new issues from bummers like me 😄 

Yeah I agree. I am waiting for a response about it from @pengx17

**Comment by pengx17** [comment]
I recently published block threading as a standalone plugin, which will always use the latest version.

**Comment by Bad3r** [comment]
@pengx17 is bullet threading going to be removed from the theme? i.e. is the new recommended method to install bullet threading separate from dev theme?

**Comment by pengx17** [comment]
The standalone plugin is just a css resource fetcher for dev theme. I will not change the fact unless there is a very strong reason

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Bad3r ***@***.***>
发送时间: Monday, January 3, 2022 10:10:27 PM
收件人: pengx17/logseq-dev-theme ***@***.***>
抄送: Peng Xiao ***@***.***>; Mention ***@***.***>
主题: Re: [pengx17/logseq-dev-theme] Selected block is not highlighted (Issue #29)


@pengx17<https://github.com/pengx17> is bullet threading going to be removed from the theme? i.e. is the new recommended method to install bullet threading separate from dev theme?

―
