### ISSUE TITLE
bullet threading misaligned when changing the font size to 20px 

### ISSUE THREAD

**Issue by jarodise** [pengx17/logseq-dev-theme#33]
the default 16px is a bit too small for my eyes to  read, but after changing the font-size to 20px, the bullet threading is misaligned. see screenshot below:

![CleanShot 2022-01-19 at 19 13 22@2x](https://user-images.githubusercontent.com/15899808/150170860-5b514a15-a19a-49bb-bab6-85df0202f983.png)

Hope this can be fixed in future iteration. Thanks!

**Comment by pengx17** [comment]
I did a rough investigation. I think we need to make sure the layout in Logseq can be more responsive to REM instead of using hard-coded lengths in pixels. This seems to be a lot of work upstream. Could you please just zoom in shortcuts to enlarge texts before this is done?

**Comment by pengx17** [comment]
> 你好，请问现在的logseq版本如何通过快捷键放大字体呀？我试了ctrl+=，没有反应。

按理说可以的，可能是与别的快捷键冲突了?
