### ISSUE TITLE
Turn off transparency on top bar

### ISSUE THREAD

**Issue by redstreet** [pengx17/logseq-dev-theme#34]
Fantastic theme all around, thank you! Especially like query boxes and titles and the task displays.

If I wanted to turn off the transparency on the very top bar, is this easy?

Would it be possible to do via the plugin config/settings json? Is that even available for themes?

If not, any leads on doing it manually is appreciated. It's rendering poorly on my particular display, and making it hard to use the otherwise wonderful theme on this particular display.

Thanks much!

**Comment by redstreet** [comment]
Ah, found the part in custom.css. Commenting it out helped:

```
/*
@supports (-webkit-backdrop-filter: blur(20px)) or (backdrop-filter: blur(20px)) {
  .cp__header,
.cp__right-sidebar-topbar,
.sidebar-item.content > div > div:first-of-type {
    -webkit-backdrop-filter: blur(20px);
    backdrop-filter: blur(20px);
    background-color: transparent;
  }
}
*/
```

Thank you!

**Comment by pengx17** [comment]
Hi, this theme is not designed to be customizable-friendly because some features are very hacky and not quite stable. But you can always override them in your custom.css file :)
For your particular issue, you need to search for `blur` keyword and reset blur & background-color properties.

**Comment by redstreet** [comment]
Got it, and that's very helpful. Thanks so much!
