### ISSUE TITLE
[Question] How to detect iOS

### ISSUE THREAD

**Issue by ivanddm** [pengx17/logseq-dev-theme#35]
Hi,

I'm using this awesome theme in the desktop app in mac and just starting trying the iOS app. At the moment, and understandably, the theme does not fit entirely well the iOS app, such as the header, and the bullet threading.

Is there a way to detect whether the app is running on the desktop or in iOS in the `custom.css` app, so for now, I can just disable any theme when running in iOS?

Thanks in advance!

**Comment by pengx17** [comment]
For now,  I recommend you to install this theme as a plugin (can be found in the marketplace) in the Desktop app and do not use custom.css `import`. 
I am not using the iOS app yet and do not know how to fix the issues, but will definitely take a look when Logseq mobile has a native sync service.  In the meantime, I have marked the ticket as 'Help wanted' to see if someone else can take a look.

**Comment by ivanddm** [comment]
Thanks a lot. I will install the theme as a plugin as suggested!
