### ISSUE TITLE
title bar's back color is white in dark mode

### ISSUE THREAD

**Issue by tianyalang** [pengx17/logseq-dev-theme#36]
In windows OS, the color of title bar is not consistent with others

![image](https://user-images.githubusercontent.com/44080909/151386499-d05def19-d87f-484a-8ef5-6520283d0b7c.png)

**Comment by pengx17** [comment]
It is an issue of Logseq itself. See https://discuss.logseq.com/t/remove-application-title-from-windows/3982/5
