### ISSUE TITLE
[Question] Disable bullet threading

### ISSUE THREAD

**Issue by luvs** [pengx17/logseq-dev-theme#39]
Hi! Is it possible to disable/remove bullet threading?

**Comment by pengx17** [comment]
Sorry, there is no easy way to disable it.

**Comment by zhengyu-yang** [comment]
I actually created a fork that removes it along with some small tweaks: https://github.com/zhengyu-yang/logseq-dev-theme
Currently, you have to load it as an unpacked plugin. However, if this is a popular demand and @pengx17 agree, I think I can publish it on the marketplace too.

**Comment by pengx17** [comment]
@zhengyu-yang hmm, you remind me that maybe we could have a separate custom.css config, like what I did for the bullet-threading.css Maybe you are interested in sending a PR instead?

**Comment by pengx17** [comment]
Fixed in https://github.com/pengx17/logseq-dev-theme/releases/tag/v1.24.0

**Comment by zhengyu-yang** [comment]
Sorry for the late reply, I can still send a PR. I added the bullet highlight effect of [logseq-laurel-theme](https://github.com/pengx17/logseq-laurel-theme) in my fork to replace the bullet threading.
