### ISSUE TITLE
When embed block，Can the extra lines in the picture be removed? not very pretty

### ISSUE THREAD

**Issue by Xuyiycl** [pengx17/logseq-dev-theme#45]
eg：
![image](https://user-images.githubusercontent.com/48081824/159422309-0a064094-5d93-4ccf-8558-d623abf9b1a3.png)

**Comment by pengx17** [comment]
Fixed by https://github.com/pengx17/logseq-dev-theme/commit/986e7913b1822aaaf9f3f44c7389758fd6963ee3
