### ISSUE TITLE
request: could you make the scroll bar start lower?

### ISSUE THREAD

**Issue by lef-est** [pengx17/logseq-dev-theme#49]
![image](https://user-images.githubusercontent.com/9643637/163682242-4b3df68a-8678-4171-a0a7-c1ec3f934bcb.png)
I think it would look nicer if it starts below the blurring top bar. Woz Theme does that.

**Comment by pengx17** [comment]
Fixed by https://github.com/pengx17/logseq-dev-theme/commit/2d48f0151a097242f0199a37fd9b5aaa13b9ca76
