### ISSUE TITLE
dates in the current month not visible in date pickers

### ISSUE THREAD

**Issue by cyb3rm4x1** [pengx17/logseq-dev-theme#53]
Dates in the current month are not visible in the date pickers under dark theme. This happen after Logseq 0.6.7.

<img width="591" alt="Screen Shot 2022-04-30 at 11 53 15 AM" src="https://user-images.githubusercontent.com/103046384/166099010-f43d078c-745d-4c3f-a1a9-da02d3ec24de.png">

**Comment by pengx17** [comment]
Thanks for rising this issue!
