### ISSUE TITLE
Support for einsenhower

### ISSUE THREAD

**Issue by chris-tkinter** [pengx17/logseq-dev-theme#6]
Hi, I really like your theme!

I have a question, what would you suggest to make this theme compatible with einsenhower matrix? Currently the theme makes the display mingled together. I am referring to this

https://discuss.logseq.com/t/css-template-eisenhower-matrix/526

Thanks!

**Comment by pengx17** [comment]
Hi, I think this is something hard to maintain. Both (dev and eisenhower-matrix) are investing heavily in CSS. I personally do not use eisenhowever-matrix but only dev theme for my workflow, so I will not consider making it compatible with other CSS themes.
Sorry about that, I am closing the issue.
