### ISSUE TITLE
请问如何设置ipad界面的正文字体大小？

### ISSUE THREAD

**Issue by xfxme** [pengx17/logseq-dev-theme#67]
我试着调整
:root {
  --ct-text-size:18px;
}
Mac 下正文能调整，但是在ipad上面不起作用。请问如何设置ipad界面的正文字体大小？

**Comment by pengx17** [comment]
https://github.com/pengx17/logseq-dev-theme/issues/33#issuecomment-1043050146 试试改一下这里看看？
