### ISSUE TITLE
Priority Mark 显示为灰色，求助

### ISSUE THREAD

**Issue by Held0n** [pengx17/logseq-dev-theme#7]
使用 [#A] 等 priority mark 显示为灰色，不知道是什么原因，可能是字体的问题。
![image](https://user-images.githubusercontent.com/43040759/130387834-3f9c83d5-7432-4186-a5ed-88ac7b2a75c2.png)
logseq version: 0.35.0
logseq-dev-theme version: 1.20.6

尝试将 logseq-dev-theme 版本切换为 1.12.0，priority mark 显示正常
![image](https://user-images.githubusercontent.com/43040759/130387967-54964736-66b7-4ccf-8e68-08410b0ea767.png)

可能是字体问题，对 css 不熟悉，求助大佬！

**Comment by pengx17** [comment]
用非emoji的方式实现了, 这个问题应该已修复。
