### ISSUE TITLE
Bullet threading conflicts with Android

### ISSUE THREAD

**Issue by ljunhui** [pengx17/logseq-dev-theme#86]
@import url("https://cdn.jsdelivr.net/gh/pengx17/logseq-dev-theme@main/bullet_threading.css");

Adding the above line to custom.css causes the right folding arrow (per https://github.com/logseq/logseq/pull/7492) to disappear.

Using Android 0.8.15.

**Comment by UNICKCHENG** [comment]
Hi @ljunhui , It does not disappear, but appears to be adjacent to the left button

![image](https://user-images.githubusercontent.com/32270702/219903674-72b8f1a4-0c11-4b36-b24c-3f1e0113a53d.png)
