### ISSUE TITLE
Apply for the maintainer of this OSS project

### ISSUE THREAD

**Issue by UNICKCHENG** [pengx17/logseq-dev-theme#89]
Hi, @pengx17 

I saw your message in discord, is it possible to apply for the maintainer of this OSS project?

I am currently maintaining logseq-developer-theme, which is a secondary development based on logseq-dev-theme upstream. I thought I might be able to help you with logseq-dev-theme.

I look forward to hearing back from you.

Have fun with your new job,

zhicheng

**Comment by pengx17** [comment]
Thanks for reaching out for help!
I think one major thing you may need to pay attention to is the release actions that are triggered automatically by commits in the master branch. The versions are generated by scanning commit messages of semantic release syntax. For example "fix: " will trigger a minor fix release and "feat" will trigger a feature release, etc.

I will grant you permission now.

**Comment by pengx17** [comment]
Invitation sent.
